version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: dejangosigehk
      POSTGRES_PASSWORD: NoqL5OOr092D
    volumes:
      - ./database:/var/lib/postgresql/data
  gunicorn:
    build: .
    # image: andrecamara/djangosige
    command: gunicorn -b 0.0.0.0:8000 djangosige.wsgi:application
    environment:
      # - DEBUG=True
      # - DJANGO_DEVELOPMENT=True
      - SECRET_KEY=0#pny4oox9s#+#5dkde25dj79b-o^sdbz4kiumg#e1qx3ky
      - ALLOWED_HOSTS='gunicorn'
      - DATABASE_URL=postgres://dejangosigehk:NoqL5OOr092D@postgres/dejangosigehk
    volumes:
      - ./:/opt/djangoSIGE/
    links:
      - postgres
    working_dir: /opt/djangoSIGE/
  nginx:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./djangosige/static/:/opt/djangoSIGE/static/
      - ./djangosige/media/:/opt/djangoSIGE/media/
    ports:
      - 6000:80
    links:
      - gunicorn
